### ISSUE TITLE
Remove Options from InstantiteMsg

### ISSUE THREAD

**Issue by siriustaikun** [LeTurt333/juno_vaults#1]
The whitelists are all required so they do not need to be options.
https://github.com/LeTurt333/juno_vaults/blob/35087ffe364e1c148b8c16739cb9dc502d288c57/juno_vaults_contract/src/contract.rs#L39-L50

**Comment by LeTurt333** [comment]
Fixed in https://github.com/LeTurt333/juno_vaults/commit/5eb997be0ab0af2f791e7b79b71d146a80df41ea
