### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by reecepbcups** [LeTurt333/juno_vaults#11]

**Comment by LeTurt333** [comment]
Documentation? 

Is this a new crate or something?

**Comment by reecepbcups** [comment]
@LeTurt333 No, I mean just docs on the control flow of what features said functions get

Both in a docs/ folder as well as function /// docs

**Comment by LeTurt333** [comment]
[Added high level overview to readme with images](https://github.com/LeTurt333/juno_vaults/commit/89e4be8e1964d5b9a6ccfbf44d7b95c9a01dfd8d)
