### ISSUE TITLE
Return exact seconds rather than EzTime

### ISSUE THREAD

**Issue by reecepbcups** [LeTurt333/juno_vaults#14]
EzTime should be done on the frontend, the contract should return exact seconds for simplisticy. Also removes casting errors that could come up with u64 -> i32 etc.

**Comment by LeTurt333** [comment]
closed in [a32fe7a](https://github.com/LeTurt333/juno_vaults/commit/a32fe7a15ba5bef309fb40984ba2cb32d2d1b4cb)
