### ISSUE TITLE
Return whitelisted listings in its own Query?

### ISSUE THREAD

**Issue by reecepbcups** [LeTurt333/juno_vaults#15]
This way the main query is not jumbled up with unique queries, then the user can go to their special page for any uniques

**Comment by LeTurt333** [comment]
I like it, short of doing some primarykey impl magic I came up with 2 ideas for this

**1) (Changes in my [last commit](https://github.com/LeTurt333/juno_vaults/blob/main/src/query.rs#L136), still needs tests)** 
- Change Listing State & Limit whitelisted_buyers to maximum of 3
- Store whitelisted_buyers in UniqueIndexes, 1 for each buyer `(buyer, listing_id)`
- Then just prefix(user_wallet).range(None - None) to get listings where a user_wallet is whitelisted
- > Need to add check that address can't be duplicated in more than 1/3 spots for a listing


**2) Just handle sorting on the UI**

---

I commented out but left the previous whitelist implementation using the Vec<Option<Addr>> incase we decide 3 whitelisted buyers isn't enough or come up with something better
