### ISSUE TITLE
Return error on dupes in ask rather than changing 

### ISSUE THREAD

**Issue by LeTurt333** [LeTurt333/juno_vaults#16]
I think we should return an error on duplicates in a createlistingmsg.ask rather than combining them (but still remove 0's), I added [a function](https://github.com/LeTurt333/juno_vaults/blob/main/src/utils.rs#L74) to do this but didn't add it in the executes to wait until we could discuss

**Comment by reecepbcups** [comment]
Ahh I missed this and created my own similar function

I'm fine with either, what ever the frontend handles better is good for me. Was just thinking combine from a UX perspective 

edit: oh it was a new function, adding in my cleanup
