### ISSUE TITLE
Future test/changes

### ISSUE THREAD

**Issue by reecepbcups** [LeTurt333/juno_vaults#20]
- duplicate token id or amount for cw20s/cw721 for ask (should error)
- altered cw20+cw721 spec, how does the contract verify (does stargaze contracts check this?) ?
- more validation for fees sent to the CPool
- possible out of gas issues if user trades a LOT of NFTs/CW20s. Set a max limit?
- in depth documentation / spec sheet

look into test on the following
```
|| Uncovered Lines:
|| src/contract.rs: 60-61, 63, 76, 87, 91, 115-116, 197, 207, 210
|| src/execute.rs: 22, 27, 53, 56-57, 81, 95, 106, 134, 187, 191-192, 204, 206, 234, 245, 247, 251, 326, 336, 339, 346, 351, 365, 368-372, 374, 377, 382, 388, 390, 392-393, 395, 398-401, 403, 405, 408, 421, 432, 464, 543, 583, 588, 598, 602-603, 609, 669, 686-687
|| src/msg.rs: 10-12, 20, 94-96
|| src/query.rs: 9, 11-15, 20-23, 39-42, 45, 47-48, 51-52, 60-62, 64, 66-69, 73-74, 76, 78, 80, 82, 84, 86, 88-91, 95, 99, 103, 107-108, 111, 114, 128-130, 133, 135-136, 140-145, 152-153, 158, 163, 166, 168, 172-175, 182, 186-187, 191
|| src/state.rs: 9, 20, 121, 133, 139
|| src/utils.rs: 84, 107, 126
|| Tested/Total Lines:
|| src/contract.rs: 57/68
|| src/execute.rs: 254/311
|| src/msg.rs: 0/7
|| src/query.rs: 21/93
|| src/state.rs: 40/45
|| src/utils.rs: 55/58
|| 
73.37% test coverage
```

**Comment by LeTurt333** [comment]
@Reecepbcups 

`altered cw20+cw721 spec, how does the contract verify (does stargaze contracts check this?) ?`

Stargaze doesn't have the same concern because it's permissioned

---

`possible out of gas issues if user trades a LOT of NFTs/CW20s. Set a max limit?`

I was thinking the same

**Comment by LeTurt333** [comment]
- [X] [duplicate token id or amount for cw20s/cw721 for ask (should error)] | [GenericBalance](https://github.com/Hypnos-Labs/fuzion_contracts/blob/main/src/state.rs#L266) | [cw20::Balance](https://github.com/Hypnos-Labs/fuzion_contracts/blob/main/src/state.rs#L367)
  
  
- [ ] altered cw20+cw721 spec, how does the contract verify (does stargaze contracts check this?) ?  
  
  
- [X] [more validation for fees sent to the CPool](https://github.com/Hypnos-Labs/fuzion_contracts/blob/main/src/utils.rs#L83)  
  
  
- [ ] possible out of gas issues if user trades a LOT of NFTs/CW20s. Set a max limit?  
  
  
- [ ] in depth documentation / spec sheet

**Comment by LeTurt333** [comment]
> * [x]  [duplicate token id or amount for cw20s/cw721 for ask (should error)] | [GenericBalance](https://github.com/Hypnos-Labs/fuzion_contracts/blob/main/src/state.rs#L266) | [cw20::Balance](https://github.com/Hypnos-Labs/fuzion_contracts/blob/main/src/state.rs#L367)
> * [x]  altered cw20+cw721 spec, how does the contract verify (does stargaze contracts check this?) ?
> * [x]  [more validation for fees sent to the CPool](https://github.com/Hypnos-Labs/fuzion_contracts/blob/main/src/utils.rs#L83)
> * [x]  possible out of gas issues if user trades a LOT of NFTs/CW20s. Set a max limit?
> * [ ]  in depth documentation / spec sheet

Added a query in both receive wrappers that all cw20/cw721's following spec will have

Other than that, the only thing I can think of would be setting up an external verification tool & bringing back the whitelist
