### ISSUE TITLE
Simplify Whitelist 

### ISSUE THREAD

**Issue by siriustaikun** [LeTurt333/juno_vaults#3]
current whitelist is over-engineered and doesn't scale well because it uses vecs. Your config query will quickly run out of gas on most nodes.
https://github.com/LeTurt333/juno_vaults/blob/35087ffe364e1c148b8c16739cb9dc502d288c57/juno_vaults_contract/src/execute.rs#L25-L67

switch this to a map with a tuple type:
```rust
const WHITELIST: Map<(AssetVariant, String), bool> = Map::new("whitelist");
```

**Comment by reecepbcups** [comment]
fixes #5 as well

**Comment by LeTurt333** [comment]
added fix here and updated tests https://github.com/LeTurt333/juno_vaults/commit/14119c631e076e5b5f14267b608b7e1a2d8baaae

used individual maps for each type for the ease of use with WHITELIST.has(deps, key)

if it looks good I'll mark this one as completed

**Comment by Reecepbcups** [comment]
@LeTurt333 What's the purpose behind an asset whitelist? 

Would be easier to just let any asset / token in listings & Buckets. Not sure why we would want to purposely not allow assets (given It’s an asset marketplace)

Just only sending juno to the community pool

**Comment by reecepbcups** [comment]
maybe just remove entirely? Ill make a PR and remove this, then we can decide
![image](https://user-images.githubusercontent.com/31943163/210129619-ddf5bc88-0d7b-4a37-b63c-440a689a96fe.png)
